[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ocp_solana = "FejBZZZmyTeqxBLEkbBHiAiHWov7MnTUznNjmi4TyRXR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
